# GitHub Sponsors and other funding links
# Add your funding links below. Uncomment the ones you want to use and add your details.
# Documentation: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: omouta
