# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
jelly = "omouta/jelly@0.3.3"
lune = "lune-org/lune@0.10.1"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
