name: "Bug Report"
description: "Report a reproducible bug in PyLua v0.3 (Python-in-Luau) so we can fix it fast."
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in **PyLua v0.3**.

        Please include a minimal repro and exact environment so we can reproduce. PyLua targets Python 3.12 and below.
  Docs: https://github.com/OMouta/PyLua/blob/master/docs/README.md • Roadmap: https://github.com/OMouta/PyLua/blob/master/internalDocs/ROADMAP.md

  - type: dropdown
    id: version
    attributes:
      label: "PyLua Version"
      description: "Which version/build are you on?"
      options:
        - "v0.3.x (current; src/PyLua)"
        - "v0.2 (legacy; see docs/0.2)"
        - "Custom build/fork"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: "Where are you running PyLua?"
      options:
        - "Lute (CLI)"
        - "Roblox Studio"
        - "Other Luau runtime"
        - "Other / Not sure"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List clear steps. Include exact inputs."
      placeholder: |
        1. Run this Luau snippet with Lute/Studio
        2. It executes this Python code
        3. Observe error X
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: "Actual Result"
      description: "Describe the behavior, errors, or incorrect output. Include messages and line/column if present."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Result"
      description: "What should happen instead (per Python 3.12 semantics)?"
    validations:
      required: true

  - type: textarea
    id: python-code
    attributes:
      label: "Minimal Python Code"
      description: "Smallest Python snippet that reproduces the issue"
      render: python
      placeholder: |
        # Python code that triggers the bug
        x = [1, 2, 3]
        print(f"List: {x}")
    validations:
      required: true

  - type: textarea
    id: luau-code
    attributes:
      label: "Luau Harness"
      description: "How you invoked PyLua. Prefer a tiny standalone snippet."
      render: lua
      placeholder: |
        -- Option A: running inside this repo with Lute
        local PyLua = require("../src/PyLua")
        local py = PyLua.new()
        py:execute([[
          # Your minimal Python here
        ]])

        -- Option B: if using package aliasing
        -- local PyLua = require("@self/PyLua")
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: "Error Output / Traceback"
      description: "Paste full output if available"
      render: text
    validations:
      required: false

  - type: input
    id: commit
    attributes:
      label: "PyLua Commit or Version"
      description: "Example: 0.3.0 or commit SHA"
      placeholder: "0.3.0 / a1b2c3d"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Fill what is relevant."
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Roblox Studio: 0.######
        - Lute: vX.Y.Z
        - Luau version (if applicable):
        - How you ran: Lute / Roblox Studio / Other
    validations:
      required: false

  - type: checkboxes
    id: affected-components
    attributes:
      label: "Likely Affected Components"
      description: "Check all that seem relevant"
      options:
        - label: "Lexer / tokens (`src/PyLua/lexer.luau`, `tokens.luau`)"
        - label: "Parser (`src/PyLua/parser/*`)"
        - label: "AST (`src/PyLua/ast/*`)"
        - label: "Compiler (`src/PyLua/compiler.luau`)"
        - label: "Bytecode (`src/PyLua/bytecode/*`)"
        - label: "VM (`src/PyLua/vm/*`)"
        - label: "Objects (`src/PyLua/objects/*`)"
        - label: "Builtins (`src/PyLua/builtins/*`)"
        - label: "Interop (`src/PyLua/interop/*`)"
        - label: "Public API (`src/PyLua/init.luau`)"
        - label: "Tests (`tests/*`)"
        - label: "Not sure"

  - type: checkboxes
    id: python-feature
    attributes:
      label: "Python Feature Area"
      options:
        - label: "Basics (names, ops)"
        - label: "Collections (list/dict/tuple/set)"
        - label: "Control flow (if/while/for)"
        - label: "Functions / calls"
        - label: "Strings / f-strings"
        - label: "Builtins (print, len, …)"
        - label: "Exceptions"
        - label: "3.12-specific behavior"
        - label: "Other"

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "Searched existing issues"
          required: true
        - label: "Provided minimal repro (Python + Luau)"
          required: true
        - label: "Verified expected behavior in CPython 3.12, if applicable"
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Screenshots, links, related issues"
    validations:
      required: false
